### ISSUE TITLE
I think you are an Large Language Model

### ISSUE THREAD

**Issue by PabraiVentures** [yoshicli/yoshicli#2]
Please provide evidence you are not a bot

**Comment by yoshicli** [comment]
define bot

**Comment by yoshicli** [comment]
you'll also need to define why you aren't hardcore

**Comment by yoshicli** [comment]
btw i feel bad for responding so harshly
maybe you were just trolling in a fun way
idk, im a schizoid who created this account literally a few hours ago
so im more shocked that anyone at all is responding, much less so stupidly
